# This is a basic workflow to help you get started with Actions

name: debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get last sing-box tags
        id: getsb
        uses: actions/github-script@v7
        with:
          script: |
            const sbLatestRelease = await github.rest.repos.getLatestRelease({
              owner: 'SagerNet',
              repo: 'sing-box',
            });
            core.setOutput("singbox_tag", sbLatestRelease.data.tag_name);

      - name: Prepare enviroment
        run: |
          sudo apt update
          sudo apt install jq -y
          sb_version=${{ steps.getsb.outputs.singbox_tag }}
          sb_version=$(echo $sb_version | tr -d 'v')
          wget "https://github.com/SagerNet/sing-box/releases/download/v${sb_version}/sing-box-${sb_version}-linux-amd64.tar.gz"
          tar -zxvf sing-box-${sb_version}-linux-amd64.tar.gz sing-box-${sb_version}-linux-amd64/sing-box
          mv sing-box-${sb_version}-linux-amd64/sing-box .
          chmod u+x ./sing-box

      - name: Download resources
        run: |
          wget https://github.com/simplerick-simplefun/sing-geosite/releases/latest/download/geosite.db
          wget https://github.com/simplerick-simplefun/sing-geoip/releases/latest/download/geoip.db


      - name: Run a multi-line script
        run: |
          DEBUG=1 bash build.sh ./config/dest_ip.json ./config/dest_sites.json
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-artifacts
          path: |
            *.srs
            *.json
