# This is a basic workflow to help you get started with Actions

name: release

on:
  workflow_dispatch:

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup enviroment
        id: setup
        run: |
          sudo apt update
          sudo apt install jq -y
          wget https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-1.9.3-darwin-amd64.tar.gz 

      - name: download resources
        id: download
        env:
          IP_CONF_LINK: ${{ secrets.SB_IP_CFG }}
          SITE_CONF_LINK: ${{ secrets.SB_SITE_CFG }}
        run: |
          wget https://github.com/simplerick-simplefun/sing-geosite/releases/latest/download/geosite.db
          wget https://github.com/simplerick-simplefun/sing-geoip/releases/latest/download/geoip.db
          echo "ip_conf_file=$(curl -s -J -O -w '%{filename_effective}' ${IP_CONF_LINK})" >> "$GITHUB_OUTPUT"
          echo "site_conf_file=$(curl -s -J -O -w '%{filename_effective}' ${SITE_CONF_LINK})" >> "$GITHUB_OUTPUT"


      - name: build
        id: build
        run: |
          echo "tag=$(date +'%Y-%m-%dT%H:%M:%S')" >> "$GITHUB_OUTPUT"
          ip_conf=${{ steps.download.outputs.ip_conf_file }}
          site_conf=${{ steps.download.outputs.site_conf_file }}
          bash build.sh "$ip_conf" "$site_conf"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-artifacts
          path: |
            *.srs
      
      - name: Push artifacts to release branch
        if: steps.build.outputs.skip != 'true'
        run: |
          git config --local user.email "13503950+simplerick-simplefun@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release
          git checkout --orphan release-orphan
          git rm -rf .
          
          git add *.srs
          
          git commit -am "Updated at $(date)"
          git branch -D release
          git branch -m release
      
      - name: Release
        if: steps.build.outputs.skip != 'true'
        id: release
        uses: softprops/action-gh-release@v2.0.6 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          name: "${{ steps.build.outputs.tag }}"
          tag_name: "${{ steps.build.outputs.tag }}"
          files: |
            *.srs